version: '3'

services:
  splunkenterprise:
    hostname: splunkenterprise
    image: splunk/splunk:6.6.3
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514

    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"